### ISSUE TITLE
DeFi smart contract needs

### ISSUE THREAD

**Issue by damip** [massalabs/massa-sc-examples#27]
By decreasing order of priority:

* Token (erc20 equivalent): urgent
* NFT

Less urgent:
* Oracle
* Multisig
* Bridge
* Swap

Every time, it needs to be an MRC .md file describing the interface (like this: https://ethereum.org/en/developers/docs/standards/tokens/erc-20/ ) together with a reference assemblyscript implementation (with comments in the code)

**Comment by gregLibert** [comment]
I propose to reuse ERC20 from https://github.com/massalabs/massa-sc-library/issues/13.

**Comment by longgamma-massa** [comment]
@damip @gregLibert I can transfer this issue into the massa-standards, which is a repo for all Massa Labs produced sc-standards. 

Atm, we published first versions of the 2 urgent ones:
1. FT
2. NFT

I need a bit more context on the need and urgency for the following proposals (for the Mainnet):
1. Oracle
2. Multisig
3. Bridge
4. Swap

**Comment by qdrn** [comment]
We (@lilyanB @leoloco) are working on a bridge right now.

**Comment by qdrn** [comment]
Let's close this because it probably belong to standards rather than examples cc @gregLibert
