### ISSUE TITLE
Check that all examples are up to date

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-sc-examples#52]
**Context**
Some examples have not been updated for 3 months.
- [x] #55 
- [x] #56
- [x] #57
- [x] #58
- [x] #59
- [ ] #60

We also need to add Ci to check regularly if examples are working:
related to https://github.com/massalabs/massa-sc-examples/issues/11

**Comment by qdrn** [comment]
Even the helloworld is not working anymore.

A minimal number of examples should always be up to date. It would also be nice to have a CI that checks which examples are working or not (even if it does not test everything).

**Comment by gregLibert** [comment]
@Ben-Rey can you modify your first comment to create a meta issue ?

You can start by adding #55 :-)
