### ISSUE TITLE
MRC721 implementation

### ISSUE THREAD

**Issue by damip** [massalabs/massa-sc-examples#6]
Once we have the specification: https://github.com/massalabs/massa-sc-examples/issues/2

Implement an example smart contract following it

**Comment by gregLibert** [comment]
Isn't [Ethereum RFC](https://eips.ethereum.org/EIPS/eip-721) enough for a first version ?

**Comment by qdrn** [comment]
Yes!

**Comment by Thykof** [comment]
This PR could already solve this issue: https://github.com/massalabs/massa-as-sdk/pull/28
