### ISSUE TITLE
update blog example

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-sc-examples#65]

**Comment by gregLibert** [comment]
@windushka blog should be listed in the [readme](https://github.com/massalabs/massa-sc-examples/blob/main/README.md).

**Comment by windushka** [comment]
> @windushka blog should be listed in the [readme](https://github.com/massalabs/massa-sc-examples/blob/main/README.md).

Done in #67

**Comment by qdrn** [comment]
Done in #67 and #66.
