### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-sc-examples#74]
See: https://github.com/massalabs/massa-sc-examples/actions/runs/4720628620/jobs/8372901436

**Comment by qdrn** [comment]
It doesn't work every-time. I don't think the issue is the CI but most likely in the network that is being used... Maybe we can retry automatically a given number of time so we know it's really an issue ?

**Comment by qdrn** [comment]
We should in any case clean the CI and remove project specific workflows (age or sum for instance). It makes more sense to use a matrix job.

**Comment by gregLibert** [comment]
> We should in any case clean the CI and remove project specific workflows (age or sum for instance). It makes more sense to use a matrix job.

Yes you're  right.

**Comment by 0xSwapFeeder** [comment]
I'm quite confused here, from our discussion here #40, we talked about the fact that having GA specific triggers helps having a clear view on history and PR's and make CI faster since it is triggered only when corresponding changes are made. I'm I wrong @gregLibert ?

**Comment by 0xSwapFeeder** [comment]
> I'm quite confused here, from our discussion here [#62 (comment)](https://github.com/massalabs/massa-sc-examples/pull/62#discussion_r1166003598) , we talked about the fact that having GA specific triggers helps having a clear view on history and PR's and make CI faster since it is triggered only when corresponding changes are made. I'm I wrong @gregLibert ?

I'd agree on the fact that it makes new examples implementation faster and easier tho.

**Comment by 0xSwapFeeder** [comment]
Another last thing, I have this example (that might not stay tho):
https://github.com/massalabs/massa-sc-examples/pull/63/files#r1178043041
Here added some specific workflow for the 'ticker-example' CI.

We might want also to update the CI of the other examples to make some (rather basic) functional testing too.

**Comment by qdrn** [comment]
> I'm quite confused here, from our discussion here [#62 (comment)](https://github.com/massalabs/massa-sc-examples/pull/62#discussion_r1166003598) , we talked about the fact that having GA specific triggers helps having a clear view on history and PR's and make CI faster since it is triggered only when corresponding changes are made. I'm I wrong @gregLibert ? I might add that it help's figuring out what specific problems occurs and where. Interesting topic about when to use matrices: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

Sorry. I'm the one to blame here. Didn't keep track of the discussion. I just wanted things to be done in the same way for the different examples. I don't have an opinion on the best way to do it.
