### ISSUE TITLE
Implement a script to deploy a DNS with blacklisted websites

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/massa-sc-examples#86]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
@B-Naoufal based on my understanding, this ticket is blocked until another one (Pierre S' PR is merged for massa-web3) could you linked it here and update the status of this one so we're not lost and can finish as soon as possilbe please? 
Cheers
